model : 'vgg16'
dataset_name : 'tiny-imagenet'
num_classes : 200
input_size: 224

epochs: 1

data_path : 'X:/myungsang/datasets/tiny_imagenet/tiny-imagenet-200/'
workers: 1 # number of workers to generate data
batch_size: 32

save_dir : './saved' # dir for saving log, weights
save_freq: 5

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

optimizer: 'adam'
optimizer_options:
  lr: 1e-3
  weight_decay: 1e-5

trainer_options:
  check_val_every_n_epoch: 5
