model : 'yolov2'
backbone: 'darknet19'
dataset_name : 'test'
input_size: 416
in_channels: 3
num_classes : 3
scaled_anchors : [[1.3221, 1.73145], [3.19275, 4.00944], [5.05587, 8.09892], [9.47112, 4.84053], [11.2364, 10.0071]]

epochs: 1000

train_list : '/home/fssv2/myungsang/datasets/tmp/train.txt'
val_list : '/home/fssv2/myungsang/datasets/tmp/val.txt'
names : '/home/fssv2/myungsang/datasets/tmp/dog.names'
workers: 0 # number of workers to generate data
batch_size: 1

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0

# experimental_options:
#   os: 'windows' # add this option if an error about NCCL occurs in windows
#   callbacks:
#     - 'SWA'

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

# optimizer: 'adam'
# optimizer_options:
#   lr: 0
#   weight_decay: 1e-5

# optimizer: 'radam'
# optimizer_options:
#   lr: 1e-3
#   weight_decay: 1e-5

optimizer: 'adamw'
optimizer_options:
  lr: 1e-3
  weight_decay: 1e-5

# optimizer: 'sgd'
# optimizer_options:
#   lr: 0
#   momentum: 0.9
#   weight_decay: 1e-5

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.9
