model : 'yolov1'
backbone: 'darknet19'
backbone_pretrained: '' # 'tiny-imagenet' or '' 
dataset_name : 'voc'
input_size: 448
in_channels: 3
num_classes : 20
num_boxes : 2
conf_threshold: 0.25

epochs: 365

train_list : '/home/fssv2/myungsang/datasets/voc/yolo_format/train.txt'
val_list : '/home/fssv2/myungsang/datasets/voc/yolo_format/val.txt'
# val_list : '/home/fssv2/myungsang/datasets/tmp/val.txt'
names : '/home/fssv2/myungsang/datasets/voc/yolo_format/voc.names'
workers: 32 # number of workers to generate data
batch_size: 64

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9
  weight_decay: 5e-3
  nesterov: True

scheduler: 'yolo_lr'
scheduler_options:
  burn_in: 1000
  steps: [40000]
  scales: [0.1]

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.96

# experimental_options:
#   os: 'windows' # add this option if an error about NCCL occurs in windows
#   callbacks:
#     - 'SWA'