model : 'yolov1'
backbone: 'darknet19'
dataset_name : 'test'
input_size: 448
in_channels: 3
num_classes : 3
num_boxes : 2

epochs: 1000

train_list : './data/train.txt'
val_list : './data/val.txt'
names : './data/test.names'
workers: 1 # number of workers to generate data
batch_size: 1

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5

# experimental_options:
#   os: 'windows' # add this option if an error about NCCL occurs in windows
#   callbacks:
#     - 'SWA'

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

optimizer: 'adam'
optimizer_options:
  lr: 1e-3
  weight_decay: 1e-5

# optimizer: 'radam'
# optimizer_options:
#   lr: 1e-3
#   weight_decay: 1e-5

# optimizer: 'sgd'
# optimizer_options:
#   lr: 1e-4
#   nesterov: true
#   momentum: 0.9
#   weight_decay: 1e-5

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [800, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 4
#   gamma: 0.9
