model : 'yolov4-tiny'
backbone: ''
backbone_pretrained: '/home/fssv2/myungsang/my_projects/PyTorch-Object-Detection/saved/yolov4-tiny_coco-person/version_0/checkpoints/pretrained_weights.pt'
dataset_name : 'focus-front'
input_size: 416
in_channels: 3
num_classes : 1
anchors : [
  [19, 66], 
  [50, 88], 
  [27, 162], 
  [45, 232], 
  [97, 142],
  [65, 263],
  [88, 308],
  [123, 344],
  [184, 374]
]
conf_threshold: 0.25

epochs: 100

train_list : '/home/fssv2/myungsang/datasets/focus/221102_D/front/train_with_neg.txt'
val_list : '/home/fssv2/myungsang/datasets/focus/221102_D/front/val.txt'
names : '/home/fssv2/myungsang/datasets/focus/221102_D/front/focus.names'
workers: 32 # number of workers to generate data
batch_size: 64

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9
  weight_decay: 1e-2
  nesterov: True

scheduler: 'yolo_lr'
scheduler_options:
  burn_in: 4000
  steps: [64000]
  scales: [0.1]

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.96

# experimental_options:
#   os: 'windows' # add this option if an error about NCCL occurs in windows
#   callbacks:
#     - 'SWA'