model : 'yolov3'
backbone: 'darknet19'
backbone_pretrained: '' # 'tiny-imagenet' or '' 
# backbone_pretrained: '/home/fssv2/myungsang/my_projects/PyTorch-Object-Detection/ckpt/darknet19-tiny-imagenet.ckpt' # 'tiny-imagenet' or '' 
dataset_name : 'visol'
input_size: 224
in_channels: 3
num_classes : 34
anchors : [
  [27, 31], 
  [29,30], 
  [33, 30], 
  [31, 33], 
  [34, 33],
  [33, 37],
  [36, 36],
  [35, 40],
  [38, 43]
]
conf_threshold: 0.25

epochs: 100

train_list : '/home/fssv2/myungsang/datasets/dacon_visol_od/train_v1.txt'
# train_list : '/home/fssv2/myungsang/datasets/dacon_visol_od/tmp.txt'
val_list : '/home/fssv2/myungsang/datasets/dacon_visol_od/val_v1.txt'
names : '/home/fssv2/myungsang/datasets/dacon_visol_od/classes.names'
workers: 32 # number of workers to generate data
batch_size: 64

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [1] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9
  weight_decay: 1e-5
  nesterov: True

scheduler: 'yolo_lr'
scheduler_options:
  burn_in: 470
  steps: [7520]
  scales: [0.1]

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.96

# experimental_options:
#   os: 'windows' # add this option if an error about NCCL occurs in windows
#   callbacks:
#     - 'SWA'