model : 'yolov4-tiny'
backbone: ''
backbone_pretrained: '/home/fssv2/myungsang/my_projects/PyTorch-Object-Detection/saved/yolov4-tiny_coco-person/version_0/checkpoints/pretrained_weights.pt'
dataset_name : 'focus-rear'
input_size: 224
in_channels: 3
num_classes : 1
anchors : [
  [8, 32], 
  [15, 67], 
  [21, 103], 
  [32, 70], 
  [30, 136],
  [78, 90],
  [44, 160],
  [64, 188],
  [94, 158]
]
conf_threshold: 0.25

epochs: 80

train_list : '/home/fssv2/myungsang/datasets/focus/221102_D/rear/train.txt'
val_list : '/home/fssv2/myungsang/datasets/focus/221102_D/rear/val.txt'
names : '/home/fssv2/myungsang/datasets/focus/221102_D/rear/focus.names'
workers: 32 # number of workers to generate data
batch_size: 64

save_dir : './saved' # dir for saving log, weights
save_freq: 5

trainer_options:
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0

accelerator: 'gpu' # 'auto', 'gpu', 'cpu'
devices: [0] # 'auto': use all, [0]: use 0 gpu, [0, 1]: use 0, 1 gpus

optimizer: 'sgd'
optimizer_options:
  lr: 1e-3
  momentum: 0.9
  weight_decay: 1e-2
  nesterov: True

scheduler: 'yolo_lr'
scheduler_options:
  burn_in: 1500
  steps: [25000]
  scales: [0.1]

# scheduler: 'multi_step'
# scheduler_options:
#   milestones: [700, 900]
#   gamma: 0.1

# scheduler: 'cosine_annealing_warm_restarts'
# scheduler_options:
#   T_0: 50
#   T_mult: 2
#   eta_min: 1e-3

# scheduler: 'cosine_annealing_warm_up_restarts'
# scheduler_options:
#   T_0: 1100
#   T_mult: 2
#   eta_max: 1e-3
#   T_up: 220
#   gamma: 0.96

# experimental_options:
#   os: 'windows' # add this option if an error about NCCL occurs in windows
#   callbacks:
#     - 'SWA'